### ISSUE TITLE
Can't get it to work anymore.

### ISSUE THREAD

**Issue by webeli** [rickharrison/create-react-app-sass#2]
Can't get it to work with the latest version of create-react-app

**Comment by rickharrison** [comment]
Thanks, I will look into it.

**Comment by rickharrison** [comment]
What exactly isn't working? I just tried it and had no problem.

**Comment by kray67** [comment]
I can't get it to work either...

'react-scripts-with-sass' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rickharrison** [comment]
Can you please post a sample project demonstrating your issue? I just started a vanilla create-react-app and had no issue.

**Comment by kray67** [comment]
It seems to have fixed itself... I ran the install a second time and it started working. Thanks!
