### ISSUE TITLE
Doesn't appear to support importing variables

### ISSUE THREAD

**Issue by nickforddev** [rickharrison/create-react-app-sass#3]
Sorry if I'm misinterpreting any features or intentions of this repo, but I'm new to Webpack (coming from Gulp) and wondering about `@import` statements. With gulp-sass, I can import scss stylesheets into other scss stylesheets, and all of the variables are imported over. That doesn't appear to be the case here, as if I try to import an .scss file, I get an error that the file is unreadable, and .css files don't have variables. 

Can you shed any light on this for me please?

**Comment by nickforddev** [comment]
Nevermind, I was misreading the error message, there were actually undefined variables.

**Comment by rickharrison** [comment]
Glad you got this figured out! Please let me know if you have any other questions/suggestions

**Comment by nickforddev** [comment]
Actually I do have a question about this, gulp-sass allows for @import statements to import .scss files, which allows things like variables to be imported from different modules. Is this at all possible with create-react-app-sass? If I try to @import a scss file I get an error saying its not a valid css file.

**Comment by jveens** [comment]
@rickharrison @nickforddesign Files should be included with the full extension: @import './partial.scss';

**Comment by nickforddev** [comment]
I was convinced that I was getting an error when attempting that, but I just confirmed that it does appear to be working as expected and can't duplicate the original issue.
