### ISSUE TITLE
New .scss files aren't compiled while webpack is running

### ISSUE THREAD

**Issue by richcsmith** [rickharrison/create-react-app-sass#4]
After running `npm start`, making changes to existing `.scss` files recompile without a problem, but nothing happens when I add and import new Sass files.

Restarting webpack (each time) does the trick, but that's less than ideal. Is there an easy fix/workaround for this?

**Comment by richcsmith** [comment]
This appears to be an issue with `node-sass`. There are a few issues already open:

1. https://github.com/sass/node-sass/issues/1575
2. https://github.com/sass/node-sass/issues/1179

**Comment by rickharrison** [comment]
This is now the recommended way to include sass: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc
