### ISSUE TITLE
Import 'variables.scss' file

### ISSUE THREAD

**Issue by EddyTheDove** [rickharrison/create-react-app-sass#5]
Hi, 
Thank you for your script. 
I am just having a hard time importing `variables.scss` file which is full of variables I defined for theming; the main reason I am using SASS. 
 
The error reads 
`File to import not found or unreadabled: ./variables.scss\nParent style sheet`
Thanks

**Comment by rickharrison** [comment]
Can you provide some sample code for what you have

**Comment by rickharrison** [comment]
This is now the recommended way to include sass: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc
