### ISSUE TITLE
--scripts-version

### ISSUE THREAD

**Issue by tuchk4** [rickharrison/create-react-app-sass#8]
According to

https://github.com/facebookincubator/create-react-app/issues/682

Maybe run create-react-app-sass via normal react-scripts but with  `--scripts-version`?

**Comment by rickharrison** [comment]
I chose to do it this way to avoid having to keep it up to date.

**Comment by rickharrison** [comment]
This is now the recommended way to include sass: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc
